apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: todoapi
spec:
 selector:
   # Selector for Pods
   app: todoapi
 ports:
   # Port Map
 - port: 80
   targetPort: 5000
   protocol: TCP
 type: LoadBalancer